// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-tA3CVIa32OWLX-zc7QfglfuRzPOfHsA',
    appId: '1:78848294941:web:854b006740d1985db2c6f4',
    messagingSenderId: '78848294941',
    projectId: 'freedgefiller',
    authDomain: 'freedgefiller.firebaseapp.com',
    storageBucket: 'freedgefiller.appspot.com',
    measurementId: 'G-YK0QNBCRYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmApQOLEjcbMsW9ToUTgejjJN3mYMFfmg',
    appId: '1:78848294941:android:f805f03ffc3c5ba7b2c6f4',
    messagingSenderId: '78848294941',
    projectId: 'freedgefiller',
    storageBucket: 'freedgefiller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHd7wFvDhmt-VN0ZzaSYZRvgYTmQEJ0Zg',
    appId: '1:78848294941:ios:71a775dcefbbaf41b2c6f4',
    messagingSenderId: '78848294941',
    projectId: 'freedgefiller',
    storageBucket: 'freedgefiller.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
